Feature structure
CarlosZ96/storebooks pull request #5
Opened 2023-08-25 21:53 UTC by CarlosZ96

React Router is configured and two routes are added: "/" and "/categories". The "Addnewbooks" and "Books" components and their content, buttons, selector paragraphs, etc. are created.

2023-08-25 22:39 UTC, Lucas-Masaba requested changes
# Hello @CarlosZ96  👋 , 

Good job so far! 👍 
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost-there](https://media.giphy.com/media/ReyD4OdRiHeLDCRaEP/giphy.gif)

## Highlights 🍾 
- Linter checks passing :heavy_check_mark: 
- Successfully created using Create React App :gear: 
- Well written commit messages :writing_hand: 

## Required Changes ♻️
_Check the comments under the review._

- [ ] All files using JSX should be named using PascalCase. This is because it helps make the code more readable, maintainable, and reusable since it is a naming convention. Please use PascalCase when naming the components you currently have i.e `books.js` and `newbook.jsx`

## Optional suggestions 💭 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Lucas-Masaba in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-25 22:39 UTC, Lucas-Masaba commented on src/App.js
> +        </ul>
[OPTIONAL]
- This would be better if it was changed into a component and imported to `App.js`. You could call the component `Navbar`

2023-08-25 22:39 UTC, Lucas-Masaba commented on src/components/books.jsx
> +            <h2>Book example</h2>
- [ ] You should create a seperate component that renders the list of books using this component. You could call it `BookList`

2023-08-26 21:20 UTC, bienvenuushindi requested changes
Hi @CarlosZ96  , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media0.giphy.com/media/cYaB1VycDbOyOiXcCx/giphy.gif"/>

## Highlights
May I highlight the following:

- The repo looks professional.:heavy_check_mark:
- There are no linter errors:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:
- Your project looks good:heavy_check_mark:

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Check the comments under the review._

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-26 21:20 UTC, bienvenuushindi commented on src/components/newbook.jsx
> +
:red_circle: [REQUESTED] Please rename this file following the PascalCase rule as it was requested by the previous reviewer :arrow_down: . Your file should be named `NewBook.jsx `instead of `newbook.jsx`
![req](https://github.com/CarlosZ96/storebooks/assets/26736582/e99d45ac-4ae3-4942-83e9-3d2d2e51b41e)

2023-08-26 21:46 UTC, mwanawabangona approved these changes
Hi @CarlosZ96 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:
Congratulations!  
![](https://camo.githubusercontent.com/d348d0cdaa16b202354d12402e048f52cd4d589b4ec0e55f07d62c2f22753376/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f336f373246634a6d4c7a4964594a646d44652f67697068792e676966)

## Highlights
*   No linter errors :heavy_check_mark:
*   Repo looks professional :briefcase:
*   Solid pull request scroll
*   Good quality commits
*   Good job implementing the requested changes!! :clap: :clap: :clap:

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-26 21:47 UTC, merged